content = open("input2.txt", encoding="utf8").read()
l = []
DNK = 'TGGGGGGGCGAAACGCCACAATGGTCCGTAAGTTATCATTGTTGGTGTGACAGCCAGGTAGAGATCACTGCCGATTATATTTGGAAGTTTCCCATGCTACTCCATCGACTTTTCCACTGAGCCACTAAACACCCTGGAATCCGATTATATTTGGAAGTTTCCCTGGTTGATCCATCGACTTTTCCACTGAATCATCTGCATTCCGACGTATGTTAGTGTTTCCACACTAAGCTCTATACTAGGGGCGATGCTTCCGACC'
d = {'modre':'TGCCGTTAAGGGGTTGTCCAAGTTAATCTAACTCCCAGCATATTCGAGAA',
'rjave':'TACGGATGTATTGGTGGGAGGCTGACTGGTCTATCCATTCTTCAGCCAGG',
'zelene':'ATGGTCCGTAAGTTATCATTGTTGGTGTGACAGCCAGGTAGAGATCACTG',
'rjava':'CCGATTATATTTGGAAGTTTCCCTGGTTGATCCATCGACTTTTCCACTGA',
'črna':'AAACGCCCCTATTAACCTTGTTCGCCCAGCCTCGCGTCGCGGAATGCCGG',
'blond':'ACCTTTTCGAGACGATCCCCTCATGCGAGGGAATTCGCACGTATTTGGAT',
'podolgovat':'AGAACCGAAGCTCTAGGAACGATCGACCCCGGTATTCCTATTTGTCACTG',
'okrogel':'ATCATCTGCATTCCGACGTATGTTAGTGTTTCCACACTAAGCTCTATACT',
'kvadratast':'TTCCGTTTTCGGCCTAGTGTTTTTGAATGTACCCGATGTGACAGGTGGAT',
'1':'GGGTCCTCCGCGGAGGTTCCTCTTACCATATTACAAAGGCGTTGTCGGCA',
'2':'TAAGCCAGAATGGTCCTGTAGCTACTACGTTCTGGCTGCCTCTATTGCTA',
'3':'CTAGCAAGGTTGGGTAGCTTGCGGTTTAACTCGCTTTAGACAGTAACATG',
'4':'GTGTCACAACAGAAATAATGATATCCATCCACTGTACCACGAAGTGGACG',
'5':'CCGATTATATTTGGAAGTTTCCCATGCTACTCCATCGACTTTTCCACTGA'}

for line in content.split('\n\n'):
    for key, value in d.items():
        if value in DNK and key not in l:
            l.append(key)

for line in content.split('\n\n'):
    attribs = line.split('\n')
    if all(x in ';'.join(attribs) for x in l):
        print(attribs[0])
